config/routes.rb
Rails.application.routes.draw do 
  patch '/flashmob/:id' => 'flashmobs#update'
  get '/flashmob/:id/edit' => 'flashmobs#edit'
  delete '/flashmobs/:id' => 'flashmobs#destroy'
  post '/flashmobs' => 'flashmobs#create'
  get '/flashmob/new' => 'flashmobs#new'
  get '/flashmob/:id/members' => 'flashmobs#members'
  get '/flashmob/:id' => 'flashmobs#show', as: 'flashmob'
  get '/flashmobs/search'
  get '/flashmobs/com'
  get '/flashmobs' => 'flashmobs#index'

  get '/comments/:id' => 'comments#show'
  post '/comments' => 'comments#create'

  get '/contact' => 'index#contact'
  post '/contact' => 'index#feedback'
  
  put 'users' => 'users#update'
  post 'members' => 'members#create'
  # Profile methods
  scope path: :profile, controller: :profile do 
    get '/' => :index
    post '/get_sign_in_panel' => :get_sign_in_panel
  end

  # API
  namespace :api do 
    namespace :v1 do
      get 'image/:id' => 'images#show'
      get 'all_flashmobs' => 'flashmobs#all_flashmobs'
      post 'create' => 'flashmobs#create'
      get 'access_token' => 'authorize#access_token'
      post 'members' => 'members#create'
      post 'add_comment' => 'comments#create'

      # Devise user
      devise_scope :user do
        post '/register' => 'registrations#create'
      end 
    end
  end

  devise_for :users, :skip => ['registrations', 'sessions']
  devise_scope :user do
    post '/users' => 'registrations#create'
    post '/sessions' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
  end

  # Devise admin
  devise_for :admins, :controllers => {:sessions => 'admin/sessions', :passwords => 'admin/passwords'}
  devise_scope :admin do
    get '/admin' => 'admin/sessions#new'
  end

  # Redirect after devise
  get '/admin/admins', as: 'admin_root', to: 'admin/admins#index'
  
  # Admin
  namespace :admin do
    resources :admins
    resources :textdescs
    resources :flashmobs

    resources :comments
    resources :members
    resources :users
    resources :feedbacks
  end
  
  root to: 'index#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include FlashmobCheck
    include BeautifulDate

    scope :last_comments, ->(lim = 5) { order('created_at DESC').limit(5) }

	belongs_to :flashmob
	belongs_to :member

	before_validation :remove_blank_spaces
	validates :text, presence: true, length: { in:0..250 }, allow_blank: false
	validates :member_id, :flashmob_id, presence: true

	validate :check_flashmob

	private
	def check_flashmob
		flashmob = cflash
		member = Member.find(member_id)
		if !member || member.flashmob_id != flashmob.id

		end
	end

	def remove_blank_spaces
		self.text = text.gsub(/\s+/, " ")
	end
end

app/controllers/admin/comments_controller.rb
#coding:UTF-8
class Admin::CommentsController < AdminController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @obj = @comment
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to admin_comment_path(@comment), notice: 'Comment was successfully created.'
    else
      @errors = @comment.errors
      render :new
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to admin_comment_path(@comment), notice: 'Comment was successfully updated.'
    else
      @errors = @comment.errors
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to admin_comments_path, notice: 'Comment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
      @errors, @name_model, @obj = @comment.errors, "comment", @comment
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:text, :member_id, :flashmob_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController	
	def show
		@comment = Comment.find(params[:id])	
		render partial: "flashmobs/comment"
	end

	def create
		c = comments_params
		c[:member_id] = session[:member_id]
		c[:flashmob_id] = params[:flashmob_id]
		comment = Comment.create(c)
		if comment.save
			render json: comment.id.to_json
		else
			render json: comment.errors.to_json
		end
	end

	private
	def comments_params
		params.require(:comment).permit(:text)
	end
end

app/helpers/comments_controller.rb
module Api
	module V1
		class CommentsController < ApplicationController
			
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <div class="row">
        <%= form_for [:admin, @comment], :html=>{:class=>"form-horizontal"} do |f| %>
          <div class="col-lg-12">
          
            <%= render "admin/form_elements/textarea", :locals=>{:name => "text", :label => "text", :f => f} %>
            
            <% if params[:action] == "edit" %>
              <div class="form-group">
                <label class="col-sm-2 control-label">Событие:</label>
                <div class="col-sm-9">
                  <a href="/admin/flashmobs/<%= @comment.flashmob_id %>" class="form-control inputmask" target="_blank"><%= @comment.flashmob.name %></a>
                </div>
              </div>
              <div class="form-group">
                <label class="col-sm-2 control-label">Участник: </label>
                <div class="col-sm-9">
                  <a href="/admin/members/<%= @comment.member_id %>" class="form-control inputmask" target="_blank"><%= @comment.member.name %></a>
                </div>
              </div>
            <% end %>
            
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-9">
                <button type="submit" class="btn btn-success waves-effect waves-light btn-md">Submit</button>
              </div>
            </div>
          </div><!-- end col -->
        <% end -%>
      </div>
    </div>
  </div>
</div>

<!-- Setting errors -->
<div class="page-errors" data-errors="<%= @errors.to_json %>" data-name="comment" style="display:none;"></div>
<script src="/assets/js/beautiful_errors.js"></script>

app/views/admin/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<div class="card-box">
	<%= link_to 'Show', admin_comment_path(@comment) %> |
	<%= link_to 'Back', admin_comments_path %>
</div>

app/views/admin/comments/index.html.erb
<div class="row">
  <div class="col-sm-12">
      <div class="card-box table-responsive">
        <div class="dropdown pull-right">
          <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">
              <i class="zmdi zmdi-more-vert"></i>
          </a>
          <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
          </ul>
        </div>

        <h4 class="header-title m-t-0 m-b-30">List of comments</h4>
        <table id="datatable-buttons" class="table table-striped table-bordered">
          <thead>
            <tr>
              
              <th>Text</th>
              <th>Member</th>
              <th>Flashmob</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @comments.each do |comment| %>
              <tr>
                <td><%= comment.text %></td>
                <td><%= comment.member_id %></td>
                <td><%= comment.flashmob_id %></td>
                <td><%= link_to edit_admin_comment_path(comment) do %><i class="zmdi zmdi-settings"></i><% end %></td>
                <td><%= button_to admin_comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } do %><i class="zmdi zmdi-delete"></i><% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br />
        <%= link_to 'New Comment', new_admin_comment_path %>
      </div>
  </div>
</div>

<%= render partial: "plugins/table_script" %>

app/views/admin/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<div class="card-box">
	<%= link_to 'Назад', admin_comments_path %>
</div>

app/views/admin/comments/show.html.erb
<div class="row">
    <div class="col-sm-8">
        <div class="bg-picture card-box">
            <div class="profile-info-name">
				<p id="notice"><%= notice %></p>				
				<p>
					<strong>Text:</strong>
				  	<%= @comment.text %>
				</p>				
				<p>
					<strong>Member:</strong>
				  	<%= @comment.member_id %>
				</p>				
				<p>
					<strong>Flashmob:</strong>
				  	<%= @comment.flashmob_id %>
				</p>
				<%= link_to 'Редактировать', edit_admin_comment_path(@comment) %> |
				<%= link_to 'Назад', admin_comments_path %>
			</div>
		</div>
	</div>
</div>