config/routes.rb
Rails.application.routes.draw do 
  patch '/flashmob/:id' => 'flashmobs#update'
  get '/flashmob/:id/edit' => 'flashmobs#edit'
  delete '/flashmobs/:id' => 'flashmobs#destroy'
  post '/flashmobs' => 'flashmobs#create'
  get '/flashmob/new' => 'flashmobs#new'
  get '/flashmob/:id/members' => 'flashmobs#members'
  get '/flashmob/:id' => 'flashmobs#show', as: 'flashmob'
  get '/flashmobs/search'
  get '/flashmobs/com'
  get '/flashmobs' => 'flashmobs#index'

  get '/comments/:id' => 'comments#show'
  post '/comments' => 'comments#create'

  get '/contact' => 'index#contact'
  post '/contact' => 'index#feedback'
  
  put 'users' => 'users#update'
  post 'members' => 'members#create'
  # Profile methods
  scope path: :profile, controller: :profile do 
    get '/' => :index
    post '/get_sign_in_panel' => :get_sign_in_panel
  end

  # API
  namespace :api do 
    namespace :v1 do
      get 'image/:id' => 'images#show'
      get 'all_flashmobs' => 'flashmobs#all_flashmobs'
      post 'create' => 'flashmobs#create'
      get 'access_token' => 'authorize#access_token'
      post 'members' => 'members#create'
      post 'add_comment' => 'comments#create'

      # Devise user
      devise_scope :user do
        post '/register' => 'registrations#create'
      end 
    end
  end

  devise_for :users, :skip => ['registrations', 'sessions']
  devise_scope :user do
    post '/users' => 'registrations#create'
    post '/sessions' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
  end

  # Devise admin
  devise_for :admins, :controllers => {:sessions => 'admin/sessions', :passwords => 'admin/passwords'}
  devise_scope :admin do
    get '/admin' => 'admin/sessions#new'
  end

  # Redirect after devise
  get '/admin/admins', as: 'admin_root', to: 'admin/admins#index'
  
  # Admin
  namespace :admin do
    resources :admins
    resources :textdescs
    resources :flashmobs

    resources :comments
    resources :members
    resources :users
    resources :feedbacks
  end
  
  root to: 'index#index'
end

app/views/admin/admins/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <div class="row">
        <%= form_for [:admin, @admin], :html=>{:class=>"form-horizontal"} do |f| %>
          <div class="col-lg-6">          
          <%= render "admin/form_elements/textfield", :locals=>{:name => "name", :label => "Name", :type => "text", :f => f} %>

          <%= render "admin/form_elements/textfield", :locals=>{:name => "email", :label => "E-mail", :type => "text", :f => f} %>
          
          <%= render "admin/form_elements/file", :locals=>{:name => "image", :label => "Image", :f => f} %>

          <%= render "admin/form_elements/password", :locals=>{:name => "password", :label => "Password", :f => f} %>

          <%= render "admin/form_elements/password", :locals=>{:name => "password_confirmation", :label => "Password Confirmation", :f => f} %>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
              <button type="submit" class="btn btn-success waves-effect waves-light btn-md">Submit</button>
            </div>
          </div>
          </div><!-- end col -->
        <% end -%>
      </div>
    </div>
  </div>
</div>

<!-- Beautiful fileupload -->
<%= render "plugins/fileupload_script" %>

<!-- Setting errors -->
<div class="page-errors" data-errors="<%= @admin.errors.to_json %>" data-name="admin" style="display:none;"></div>
<script src="/assets/js/beautiful_errors.js"></script>

app/views/admin/admins/edit.html.erb
<h1>Edit Admin</h1>

<%= render 'form' %>

<div class="card-box">
	<%= link_to 'Show', admin_admin_path(@admin) %> |
	<%= link_to 'Back', admin_admins_path %>
</div>

app/views/admin/admins/index.html.erb
<div class="row">
  <div class="col-sm-12">
      <div class="card-box table-responsive">
        <div class="dropdown pull-right">
          <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">
              <i class="zmdi zmdi-more-vert"></i>
          </a>
          <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
          </ul>
        </div>

        <h4 class="header-title m-t-0 m-b-30">List of admins</h4>
        <table id="datatable-buttons" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Created At</th>
              <th>Updated At</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @admins.each do |admin| %>
              <tr>
                <td><%= admin.name %></td>
                <td><%= admin.beautiful_created_at %></td>
                <td><%= admin.beautiful_updated_at %></td>
                <td><%= link_to edit_admin_admin_path(admin) do %><i class="zmdi zmdi-settings"></i><% end %></td>
                <td><%= link_to admin_admin_path(admin), method: :delete, data: { confirm: 'Are you sure?' } do %><i class="zmdi zmdi-delete"></i><% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br />
        <%= link_to 'New Admin', new_admin_admin_path %>
      </div>
  </div>
</div>

<%= render "plugins/table_script" %>

app/views/admin/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<div class="card-box">
	<%= link_to 'Назад', admin_admins_path %>
</div>

app/views/admin/admins/show.html.erb
<div class="row">
    <div class="col-sm-8">
        <div class="bg-picture card-box">
            <div class="profile-info-name">
				<p id="notice"><%= notice %></p>				
				<p>
					<strong>Name:</strong>
				  	<%= @admin.name %>
				</p>
				<%= link_to 'Редактировать', edit_admin_admin_path(@admin) %> |
				<%= link_to 'Назад', admin_admins_path %>
			</div>
		</div>
	</div>
</div>