config/routes.rb
Rails.application.routes.draw do 
  patch '/flashmob/:id' => 'flashmobs#update'
  get '/flashmob/:id/edit' => 'flashmobs#edit'
  delete '/flashmobs/:id' => 'flashmobs#destroy'
  post '/flashmobs' => 'flashmobs#create'
  get '/flashmob/new' => 'flashmobs#new'
  get '/flashmob/:id/members' => 'flashmobs#members'
  get '/flashmob/:id' => 'flashmobs#show', as: 'flashmob'
  get '/flashmobs/search'
  get '/flashmobs/com'
  get '/flashmobs' => 'flashmobs#index'

  get '/comments/:id' => 'comments#show'
  post '/comments' => 'comments#create'

  get '/contact' => 'index#contact'
  post '/contact' => 'index#feedback'
  
  put 'users' => 'users#update'
  post 'members' => 'members#create'
  # Profile methods
  scope path: :profile, controller: :profile do 
    get '/' => :index
    post '/get_sign_in_panel' => :get_sign_in_panel
  end

  # API
  namespace :api do 
    namespace :v1 do
      get 'image/:id' => 'images#show'
      get 'all_flashmobs' => 'flashmobs#all_flashmobs'
      post 'create' => 'flashmobs#create'
      get 'access_token' => 'authorize#access_token'
      post 'members' => 'members#create'
      post 'add_comment' => 'comments#create'

      # Devise user
      devise_scope :user do
        post '/register' => 'registrations#create'
      end 
    end
  end

  devise_for :users, :skip => ['registrations', 'sessions']
  devise_scope :user do
    post '/users' => 'registrations#create'
    post '/sessions' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
  end

  # Devise admin
  devise_for :admins, :controllers => {:sessions => 'admin/sessions', :passwords => 'admin/passwords'}
  devise_scope :admin do
    get '/admin' => 'admin/sessions#new'
  end

  # Redirect after devise
  get '/admin/admins', as: 'admin_root', to: 'admin/admins#index'
  
  # Admin
  namespace :admin do
    resources :admins
    resources :textdescs
    resources :flashmobs

    resources :comments
    resources :members
    resources :users
    resources :feedbacks
  end
  
  root to: 'index#index'
end

app/models/user.rb
class User < ActiveRecord::Base
	include Password
	include Rank
 	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	mount_uploader :image, AdminUploader
	has_many :flashmobs, dependent: :destroy
	has_one :api_key

	validates :name, presence: true
	validates :phone, format: { with: /\A\d{8,14}\z/ }, uniqueness: true # only numbers
	validates :rank, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: RANK.count - 1 }
end

app/controllers/admin/users_controller.rb
#coding:UTF-8
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    @obj = @user
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_path(@user), notice: 'User was successfully created.'
    else
      @user = @user.errors
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: 'User was successfully updated.'
    else
      @user = @user.errors
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @errors, @name_model, @obj = @user.errors, "user", @user
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :phone, :rank, :image)
    end
end

app/controllers/api/v1/users_controller.rb
module Api
	module V1
		class UsersController < ApplicationController
			# OOoops, i need to use OAuth, but not today. Bye!
			def update
				up = User.reset_password(user_params)
				if current_user.update_attributes(up)
					render :json => current_user.to_json
				else
					render :json => current_user.errors.to_json, status: 422
				end
			end

			private
			def user_params
				params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation)
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# OOoops, i need to use OAuth, but not today. Bye!
	def update
		up = User.reset_password(user_params)
		if current_user.update_attributes(up)
			render :json => current_user.to_json
		else
			render :json => current_user.errors.to_json, status: 422
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <div class="row">
        <%= form_for [:admin, @user], :html=>{:class=>"form-horizontal"} do |f| %>
          <div class="col-lg-12">
          
          <%= render "admin/form_elements/textfield", :locals=>{:name => "name", :label => "name", :f => f} %>
          
          <%= render "admin/form_elements/textfield", :locals=>{:name => "phone", :label => "phone", :f => f} %>
          
          <%= render "admin/form_elements/textfield", :locals=>{:name => "rank", :label => "rank", :f => f} %>
          
          <%= render "admin/form_elements/file", :locals=>{:name => "image", :label => "image", :f => f} %>
          
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-9">
              <button type="submit" class="btn btn-success waves-effect waves-light btn-md">Submit</button>
            </div>
          </div>
          </div><!-- end col -->
        <% end -%>
      </div>
    </div>
  </div>
</div>


<!-- Beautiful fileupload -->
<%= render "plugins/fileupload_script" %>

<!-- Setting errors -->
<div class="page-errors" data-errors="<%= @errors.to_json %>" data-name="user" style="display:none;"></div>
<script src="/assets/js/beautiful_errors.js"></script>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<div class="card-box">
	<%= link_to 'Show', admin_user_path(@user) %> |
	<%= link_to 'Back', admin_users_path %>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-sm-12">
      <div class="card-box table-responsive">
        <div class="dropdown pull-right">
          <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">
              <i class="zmdi zmdi-more-vert"></i>
          </a>
          <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
          </ul>
        </div>

        <h4 class="header-title m-t-0 m-b-30">List of users</h4>
        <table id="datatable-buttons" class="table table-striped table-bordered">
          <thead>
            <tr>
              
              <th>Name</th>
              <th>Phone</th>
              <th>Rank</th>
              <th>Image</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.phone %></td>
                <td><%= user.rank %></td>
                <td><%= user.image %></td>
                <td><%= link_to edit_admin_user_path(user) do %><i class="zmdi zmdi-settings"></i><% end %></td>
                <td><%= link_to admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } do %><i class="zmdi zmdi-delete"></i><% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br />
        <%= link_to 'New User', new_admin_user_path %>
      </div>
  </div>
</div>

<%= render partial: "plugins/table_script" %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<div class="card-box">
	<%= link_to 'Назад', admin_users_path %>
</div>

app/views/admin/users/show.html.erb
<div class="row">
    <div class="col-sm-8">
        <div class="bg-picture card-box">
            <div class="profile-info-name">
				<p id="notice"><%= notice %></p>				
				<p>
					<strong>Name:</strong>
				  	<%= @user.name %>
				</p>				
				<p>
					<strong>Phone:</strong>
				  	<%= @user.phone %>
				</p>				
				<p>
					<strong>Rank:</strong>
				  	<%= @user.rank %>
				</p>				
				<p>
					<strong>Image:</strong>
				  	<%= @user.image %>
				</p>
				<%= link_to 'Редактировать', edit_admin_user_path(@user) %> |
				<%= link_to 'Назад', admin_users_path %>
			</div>
		</div>
	</div>
</div>